import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { chromium } from '@playwright/test';
import { createPlanServer } from '../server.mjs';
const key='test-only-owner-key-0123456789abcdef0123456789';
test('full workspace shares default to Viewing, edit the same data, isolate local state, and revoke access',async()=>{
const server=createPlanServer({ownerKey:key,dbPath:':memory:'});server.listen(0,'127.0.0.1');await once(server,'listening');
const base='http://127.0.0.1:'+server.address().port;let browser;
try{
browser=await chromium.launch({channel:'msedge',headless:true});
const owner=await browser.newContext(),page=await owner.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('#connectCloud').click();await page.waitForFunction(()=>!document.querySelector('#loginCloud').disabled);
await page.locator('#ownerKey').fill(key);await page.locator('#loginCloud').click();await page.waitForFunction(()=>!document.querySelector('#connectForm').closest('dialog').open);
await page.evaluate(()=>{data.W1.push([1,'Category','Shared topic','Details','Owner','2026-09-08','2026-09-10','2026-09-08','WIP','Next','']);data['Next 3 Weeks'].push([1,'Next category','Future topic','Future details','Owner','High','WIP','','','']);dailyPlans['2026-09-08']=[{title:'Calendar topic'}];save();render();selectedDate='2026-09-08';calendarMonth=new Date('2026-09-01T12:00:00');showCalendar(true);});
page.once('dialog',d=>d.accept());await page.locator('#shareCloud').click();await page.locator('#shareLink').waitFor({state:'visible'});const link=await page.locator('#shareLink').inputValue();
assert.match(link,/#share=[a-f0-9]{64}$/);
const visitor=await browser.newContext();await visitor.addInitScript(()=>{localStorage.setItem('financePlanProductionV1','{"Personal":[]}');localStorage.setItem('personal-marker','unchanged');});
const view=await visitor.newPage();view.on('pageerror',e=>errors.push(e.message));await view.goto(link);await view.locator('#workspaceMode').waitFor();
assert.equal(await view.locator('#workspaceMode').inputValue(),'viewing');assert.equal(await view.locator('#calendarView').isVisible(),true);await view.getByText('Calendar topic',{exact:true}).waitFor();
await view.getByText('Calendar topic',{exact:true}).click();assert.equal(await view.locator('#todoDialog').evaluate(e=>e.open),false);
await view.locator('[data-check-todo]').click({force:true});assert.equal(await view.evaluate(()=>dailyPlans['2026-09-08'][0].completed),undefined);
await view.locator('#dashboardBtn').click();assert.equal(await view.locator('#dashboardView').isVisible(),true);
await view.locator('#weeklyBtn').click();await view.getByRole('cell',{name:'Shared topic',exact:true}).waitFor();
await view.locator('[data-tab="Next 3 Weeks"]').click();await view.getByRole('cell',{name:'Future topic',exact:true}).waitFor();await view.locator('[data-tab="W1"]').click();
await view.locator('#addBtn').click({force:true});assert.equal(await view.locator('#editDrawer').evaluate(e=>e.classList.contains('open')),false);
await view.getByRole('cell',{name:'Shared topic',exact:true}).dblclick();assert.equal(await view.locator('#editDrawer').evaluate(e=>e.classList.contains('open')),false);
const before=await view.evaluate(()=>stateJSON());await view.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true})));assert.equal(await view.evaluate(()=>stateJSON()),before);
assert.equal(await view.locator('#sharedSave').isDisabled(),true);
await view.locator('#workspaceMode').selectOption('editing');await view.waitForFunction(()=>window.sharedSession.editing);
await view.getByRole('cell',{name:'Shared topic',exact:true}).dblclick();await view.locator('#rowForm [name="f2"]').fill('Leader edited topic');await view.locator('#rowForm button[type="submit"]').click();
await view.locator('#sharedSave').click();await view.waitForFunction(()=>document.querySelector('#saveState').textContent.startsWith('Latest cloud save'));
await page.getByRole('button',{name:'Close',exact:true}).last().click();await page.locator('#weeklyBtn').click();await page.getByRole('cell',{name:'Leader edited topic',exact:true}).waitFor();
assert.equal(await view.evaluate(()=>localStorage.getItem('financePlanProductionV1')),'{"Personal":[]}');assert.equal(await view.evaluate(()=>localStorage.getItem('personal-marker')),'unchanged');
const token=new URL(link).hash.slice(7);const forbidden=await fetch(base+'/api/workspace',{headers:{Authorization:'Bearer '+token}});assert.equal(forbidden.status,401);
const third=await browser.newContext(),other=await third.newPage();await other.goto(link);await other.locator('#workspaceMode').waitFor();assert.equal(await other.locator('#workspaceMode').inputValue(),'viewing');
await other.locator('#workspaceMode').selectOption('editing');await other.waitForFunction(()=>window.sharedSession.editing);
await other.evaluate(()=>{data.W1[0][2]='Second editor';save();render();});await other.locator('#sharedSave').click();await other.waitForFunction(()=>document.querySelector('#saveState').textContent.startsWith('Latest cloud save'));
await view.evaluate(()=>{data.W1[0][2]='Unsaved first editor';save();render();});await view.locator('#sharedSave').click();await view.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('Cloud data changed'));
await visitor.setOffline(true);await view.locator('#sharedSave').click();await view.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('Cannot reach cloud'));await visitor.setOffline(false);
await page.locator('#connectCloud').click();page.once('dialog',d=>d.accept());await page.locator('#revokeCloud').click();await page.getByText('All share links revoked.',{exact:true}).waitFor();
await other.evaluate(()=>{data.W1[0][2]='After revocation';save();render();});await other.locator('#sharedSave').click();await other.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('does not allow editing'));assert.equal(await other.locator('#workspaceMode').inputValue(),'viewing');
const invalid=await third.newPage();await invalid.goto(link);await invalid.getByText('Workspace unavailable',{exact:true}).waitFor();assert.equal(await invalid.locator('#weeklyView').count(),0);
assert.deepEqual(errors,[]);
}finally{await browser?.close();server.close();await once(server,'close');}
});
